# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example@123!
    ports:
      - 3306:3306
    # (this is just an example, not intended to be a production configuration)