version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234@Abc
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql  # Thay đổi "/path/to/mysql/data" thành đường dẫn đến thư mục bạn muốn dùng

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
